### PR TITLE
Add contentType and magic checks to gltf-binary determination

### PR DESCRIPTION
**Pull request by camnewnham**
Hey @atteneder 
This PR is intended to add some further checks to determining whether a downloaded file is a gltf or glb.

It adds the contentType field to IDownload and checks it against `model/gltf-binary` and also checks for the glb magic as a last resort (as it's reasonable to expect that the content type may just be `application/octet-stream` if the server has not configured this).

### CODE REVIEW

**Comment by atteneder** [comment]
Hi @camnewnham,

Thank you for your effort to make glTFast better!

Am I right when saying your PR tries to solve the following problem:

> Whether the glTF is binary or not cannot be derived from the URL (since it does not contain a file extension extension anywhere).

I'm afraid accessing `download.data` for the magic-check might have a severe performance overhead (if another copy of the file is created in memory), but we'd have to check!
If this turns out to be unproblematic, wouldn't it be best to derive the type solely on the magic-check?

If this is indeed problematic, overriding via mime-type from the server's contentType is a good solution! (another solution would be to create a custom DownloadHandler implementation; I've made a concept of this once, but it's still in the drawer)

I'm hesitant to the idea of passing a (mime-type) string around. How about this instead:

```csharp
public bool? isBinary {
    get {
        if(success) {
            var contentType = request.GetResponseHeader("ContentType");
            if(contentType==GLB_MIME) return true;
            if(contentType==GLTF_MIME) return false;
        }
        return null;
    }
}
```

This would allow explicitely setting the glTF OR glTF-binary without implicit assumptions (not GLB_MIME => glTF).

Let me know your thoughts.

**Comment by camnewnham** [comment]
Good suggestions!

While not 100% sure, from a brief look at what I could find of the Unity [DownloadHandler](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Modules/UnityWebRequest/Public/DownloadHandler/DownloadHandler.bindings.cs) it looks like fetching the data is an extern call and subsequently likely requires a memcpy, so should not be enabled as a check by default.

Moving the binary type determination to the downloadhandler also makes sense as it is easier for the user to override (i.e. if they _know_ to expect a binary even if the server provides no clear differentiation).

I'll make some adjustments and update this PR.

**Comment by camnewnham** [comment]
I've adjusted the implementation based on this discussion. At the moment, the file type determination is split between the download provider (which checks the `Content-Type` header) and the `GLTFast` class, which checks the URL and extension. 

Another option would be to move _all_ of the checks to the download provider, and have `isBinary` as a `bool` rather than a `bool?`. To me this seams neater - but also adds slightly more work to implement a custom download provider. Would you prefer this, or are you happy with the current implementation as in this PR?

**Comment by atteneder** [comment]
I made a minor fix, rebased and merged fast-forward, so no need to merge this PR.
Will be in 2.2.0 and you have an entry in the ChangeLog.
Thank you very much!

**Pull request closed without merging**
