### PR TITLE
async AddBlendShapeFrame

### PR DESCRIPTION
**Pull request by EricBeetsOfficial-Opuscope**
There is no more crash with a huge blendshaped model, but it's lag more and more :\

### CODE REVIEW

**Comment by EricBeetsOfficial-Opuscope** [comment]
Hello !

Not sure to understand how to use the `IDeferAgent`, if I try to use it (in GltfImport.cs) like:
```
var primitive = await primitiveContext.CreatePrimitive();
await defaultDeferAgent.BreakPoint();
```
the model import failed ...

I wanted to attach a demo model (big blendshape model) which is too big for github :\, do you have an email (to share a gdrive link) ?

Eric

**Comment by atteneder** [comment]
Hi Eric,

sorry for the long wait. I had a look at your work.

I rebased it onto `main` and incorporated the `IDeferAgent` mechanism (see [my feature/blendshape_await branch](https://github.com/atteneder/glTFast/tree/feature/blendshape_await)).

Your solution would pause for the next frame after each blend shape. That's bad for models with small blend shapes that wouldn't take a long time to add.

I profiled the loading process on the sample file you mailed me (the flag). It won't load faster due to my change. The time it takes to add a blend shape seems to increase with each addition. With my change the first 3 blend shapes are added within one frame, but (4ms, 7ms, 10ms), but two frames later the time per blend shape is already up to 18ms from then on there's no real difference anymore. Overall it still takes around 50 seconds on my machine to load.

I'm afraid we're limited by the Mesh API, but I'll ask internally if there's a better solution.

If the performance tests show no regressions, I'll merge my improved version of your branch soonish.

Thanks!

**Comment by EricBeetsOfficial-Opuscope** [comment]
Great ! I didn't understand how to use `IDeferAgent`, I got it now ;).

I know, it's not a very good comparaison, but in another project where we used UnityGLTF (from Khronos), I added a delay (`await Task.Delay(100, CancellationToken.None)`) in a loop of the `ConstructUnityMesh` function, where blendshapes are added. It was producing a longer loading, but without freezes. Maybe it could help you ..

**Comment by atteneder** [comment]
> I know, it's not a very good comparaison, but in another project where we used UnityGLTF (from Khronos), I added a delay (`await Task.Delay(100, CancellationToken.None)`) in a loop of the `ConstructUnityMesh` function, where blendshapes are added. It was producing a longer loading, but without freezes. Maybe it could help you ..

So what you're doing there is after some computational work is done, you pause loading for 100 ms. During that time a couple of frames will be rendered (~6 at 60 fps). This way only every 7th frame will stutter, which makes it appear more fluent (at the cost of way longer loading times).

This is a design decision that may work well for some/you, but I cannot do it that way.

Luckily the IDeferAgent pattern allows you to create your own implementation that does exactly this. Even better, not only for blend shapes, but in all places glTFast might defer work to the next frame. So feel free to implement this 100ms wait behavior in a custom IDeferAgent.

hth

**Comment by atteneder** [comment]
Merged manually.

Thanks @EricBeetsOfficial-Opuscope !

**Pull request closed without merging**
