### PR TITLE
Trying run dots inside of glTFast scripts

### PR DESCRIPTION
**Pull request by juancarlosgermano**
I create a new branch called "gltf_dots". Have a lot of commented codes (that will break in the standard load) trying to run in a JobSystem. I add a question on this issue: https://github.com/atteneder/glTFast/issues/92#issuecomment-715601151

@atteneder, Check out!

### CODE REVIEW

**Comment by juancarlosgermano** [comment]
Ignore last commit comment, I sent without finishing commenting.

**Comment by atteneder** [comment]
I'm confused about two PRs within an hour. How does this compare to #94? Aren't they conflicting?

**Comment by juancarlosgermano** [comment]
This one has issue which I comment here: https://github.com/atteneder/glTFast/issues/92#issuecomment-715601151?.

And this PR was created with a branch called "gltf_dots" on my fork and that already has the PR https://github.com/atteneder/glTFast/pull/94.

**Comment by atteneder** [comment]
Thanks for your contribution! You were too soon to the party though :)

See the new DOTS code in [Runtime/Scripts/DOTS](https://github.com/atteneder/glTFast/tree/main/Runtime/Scripts/DOTS)

**Pull request closed without merging**
