### PR TITLE
Add URP Lit shader material

### PR DESCRIPTION
**Pull request by wonkee-kim**
## Context
URP glTF shaders that use ShaderGraph have bad performance on pixel shader. It drops frame rate much especially if there are alpha-blend surfaces that cause pixel overdraw.

This PR contains new URP shaders that are based on Unity's Lit shader and Unlit shader.

## Changes
Main changes from the original Lit/Unlit shaders are UV transform(channel selector and rotation) for each texture.
The new Lit shader supports `KHR_materials_unlit`, `KHR_materials_pbrSpecularGlossiness` and `KHR_materials_transmission`.
Transmission is very approximate and didn't consider using CameraOpaqueTexture.

## How to use
config
Added a config file under `glTFast\Runtime\Scripts\Material\Resources` and disabling `Use Shader Graph Material` will generate the new Lit shader based materials.

### CODE REVIEW

**Comment by atteneder** [comment]
HI @wonkee-kim ,

Thanks for your contribution. Some questions first:

- Indeed the glTF SG materials are reported to have bad performance. I'm wondering if they can be optimized at first though. How did you came to the conclusion that replacing them with Lit-based shaders is the best way forward?
- I assume you took the original URP-Lit shader and adopted them. Can you tell me which URP version you used? I'm asking because I have to make sure that they work across URP versions (starting 2020 LTS, I'd say).
- In case we agree that those shaders are "Lit" (i.e. superior), I'd rather work on feature parity and dismiss the SG ones
- In case we decide to keep both, as you intended, we probably have to make the setting a multiple-choice field, since more options (Original Lit/Standard or custom ones) are coming.

Thanks

**Comment by wonkee-kim** [comment]
> HI @wonkee-kim ,
> 
> Thanks for your contribution. Some questions first:
> 
> * Indeed the glTF SG materials are reported to have bad performance. I'm wondering if they can be optimized at first though. How did you came to the conclusion that replacing them with Lit-based shaders is the best way forward?
> * I assume you took the original URP-Lit shader and adopted them. Can you tell me which URP version you used? I'm asking because I have to make sure that they work across URP versions (starting 2020 LTS, I'd say).
> * In case we agree that those shaders are "Lit" (i.e. superior), I'd rather work on feature parity and dismiss the SG ones
> * In case we decide to keep both, as you intended, we probably have to make the setting a multiple-choice field, since more options (Original Lit/Standard or custom ones) are coming.
> 
> Thanks

Hi Atteneder, thank you for reviewing.

- I guess the bad performance is coming from uv transform (not tested though), and shader graph is somehow not very optimized. We need to support gltf's uv channel selector and uv rotation for each texture and maybe we could optimize it by using CustomFunction node for the uv transform instead of your TextureTransform Sub Graphs.

- I copied Lit/Unlit shaders from URP version 12.1.7, which is the current 2021 LTS's URP version.
- I haven't tested the shader on old URP versions. I implemented these shaders for an internal use and didn't have enough time to make it compatible with other versions.

- So that's why I added the configuration file (`glTFastUniversalRPMaterialConfig.asset`) and disabled by default and trying to upstream to your repository because of maintenance issue.
I could investigate optimizing SG materials, or make Lit shader compatible with other URP versions, but currently I have to change our project's RenderPipeline to URP ASAP and I thought using Lit shader instead of SG will perform the best.

Thank you.

**Comment by atteneder** [comment]
Thanks for you feedback. I think we should definitely investigate and understand why exactly the SG materials perform worse before going forward.
Not that I'm against introducing better shaders, but this solution is probably not that compatible across versions of SRPs.

**Comment by wonkee-kim** [comment]
I agree this shader will have version compatibility issue. I will cancel this PR.

**Pull request closed without merging**
